services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.no
    container_name: frontend-static
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "80:80"
