CREATE DATABASE IF NOT EXISTS content_db;
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS social_db;
CREATE DATABASE IF NOT EXISTS message_db;
CREATE DATABASE IF NOT EXISTS log_db;