export const USER_SERVICES = {
  CLIENT: 'USER_CLIENT',
  PORT: 3001,
};

export const AUTH_SERVICES = {
  CLIENT: 'AUTH_CLIENT',
  PORT: 3002,
};

export const LOG_SERVICES = {
  CLIENT: 'LOG_CLIENT',
  PORT: 3005,
};

export const CONTENT_SERVICES = {
  CLIENT: 'CONTENT_CLIENT',
  PORT: 3006,
};

export const HISTORY_SERVICES = {
  CLIENT: 'HISTORY_CLIENT',
  PORT: 3007,
};

export const BOARD_SERVICES = {
  CLIENT: 'BOARD_CLIENT',
  PORT: 3008,
};
export const CONNECT_SERVICES = {
  CLIENT: 'CONNECT_CLIENT',
  PORT: 3009,
};
