export const USER_SERVICES = {
  CLIENT: 'USER_CLIENT',
  PORT: 3001,
};

export const AUTH_SERVICES = {
  CLIENT: 'AUTH_CLIENT',
  PORT: 3002,
};

export const LOG_SERVICES = {
  CLIENT: 'LOG_CLIENT',
  PORT: 3005,
};

export const CONTENT_SERVICES = {
  CLIENT: 'CONTENT_CLIENT',
  PORT: 3006,
};

export const HISTORY_SERVICES = {
  CLIENT: 'HISTORY_CLIENT',
  PORT: 3007,
};

export const BOARD_SERVICES = {
  CLIENT: 'BOARD_CLIENT',
  PORT: 3008,
};
export const CONNECT_SERVICES = {
  CLIENT: 'CONNECT_CLIENT',
  PORT: 3009,
};
export const REPORT_SERVICES = {
  CLIENT: 'REPORT_CLIENT',
  PORT: 3010,
};
export const ALGO_SERVICES = {
  CLIENT: 'ALGO_CLIENT',
  PORT: 3011,
};
export const SSE_SERVICES = {
  CLIENT: 'SSE_CLIENT',
  PORT: 3012,
};
export const SOCIAL_SERVICES = {
  CLIENT: 'SOCIAL_CLIENT',
  PORT: 3013,
};
export const COMMENT_SERVICES = {
  CLIENT: 'COMMENT_CLIENT',
  PORT: 3014,
};
